/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type UserRole = 'admin' | 'manager' | 'staff';

export interface UserPermissions {
  canDeleteVoucher: boolean;
  canEditVoucher: boolean;
  canManageOptions: boolean;
  canManageStaff: boolean;
  canEditInvoice: boolean;
  canDeleteInvoice: boolean;
}

export interface User {
  id: string;
  username: string;
  password?: string; // Stored securely in client-side state for local auth demo
  name: string;
  role: UserRole;
  permissions: UserPermissions;
  createdAt: string;
}

export type PaymentStatus = 'Paid' | 'Unpaid' | 'Pending' | 'Partial' | 'Collect';
export type Language = 'TH' | 'EN';

export interface Voucher {
  id: string; // Internal unique ID
  voucherNo: string; // Automatic generated code (KNC-YYYYMMDD-XXXX)
  externalVoucherNo: string; // เลขวอเชอร์นอก (custom or autogenerated)
  tourName: string; // Tour name / Program (ชื่อทัวร์ / โปรแกรมทัวร์)
  agentName: string; // Agent / Walk-in
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  serviceDate: string; // YYYY-MM-DD
  pickupTime: string; // HH:MM
  vehicleType: string; // ประเภทยานพาหนะ
  pickupVehicle: string; // internal only
  dropoffVehicle: string; // internal only
  driverCount: number; // จำนวนคนขับ
  driverPrice: number; // ราคาคนขับ
  pillionCount: number; // จำนวนคนซ้อน
  pillionPrice: number; // ราคาคนซ้อน
  pickupLocation: string; // จุดรับ
  dropoffLocation: string; // จุดส่ง
  paymentStatus: PaymentStatus;
  depositAmount?: number; // จำนวนเงินมัดจำ
  collectAmount?: number; // จำนวนเงินที่เก็บจากลูกค้า
  sendEmail: boolean;
  language: Language;
  notes: string; // หมายเหตุ / สถานที่นัดพบ
  lineId?: string;
  whatsappId?: string;
  wechatId?: string;
  lineQrUrl?: string; // Base64 data URL
  whatsappQrUrl?: string; // Base64 data URL
  wechatQrUrl?: string; // Base64 data URL
  createdAt: string;
  createdBy: string; // Username of creator
}

export interface Expense {
  id: string;
  date: string; // YYYY-MM-DD
  category: string; // หมวดหมู่รายจ่าย
  amount: number;
  description: string;
  createdAt: string;
  createdBy: string;
}

export interface MasterData {
  tours: string[];
  agents: string[];
  vehicles: string[];
  vehicleTypes: string[];
  expenseCategories: string[];
}

export interface InvoiceItem {
  id: string;
  description: string;
  quantity: number;
  rate: number;
}

export interface Invoice {
  id: string;
  invoiceNo: string;
  invoiceDate: string;
  dueDate: string;
  clientName: string;
  agentName: string;
  clientPhone: string;
  clientEmail: string;
  clientAddress: string;
  items: InvoiceItem[];
  bankName: string;
  accountName: string;
  accountNo: string;
  notes: string;
  taxPercent: number;
  discount: number;
  isPaid: boolean;
  watermarkType?: 'PAID' | 'DEPOSIT' | 'UNPAID' | 'NONE';
  selectedVoucherId?: string;
  createdAt: string;
  createdBy: string;
}

export interface SystemSettings {
  companyName: string;
  registrationNo: string;
  address: string;
  phone: string;
  whatsapp: string;
  officePhone: string;
  email: string;
  website: string;
  logoUrl?: string; // Base64 data URL
  lineQrUrl?: string; // Base64 data URL
  whatsappQrUrl?: string; // Base64 data URL
  wechatQrUrl?: string; // Base64 data URL
  lineId?: string;
  whatsappId?: string;
  wechatId?: string;
  bankName?: string;
  accountName?: string;
  accountNo?: string;
  paymentInstructions?: string;
  paymentQrUrl?: string; // Base64 data URL of payment QR Code
}

export interface UserActivityLog {
  id: string;
  userId: string;
  username: string;
  name: string;
  action: 'login' | 'logout';
  timestamp: string; // ISO String
}


